### ISSUE TITLE
Integrate hugging face accelerate as the backend for DDP and TPU training

### ISSUE THREAD

**Issue by onkarm5** [Atharva-Phatak/torchflare#480]
##  Description of Feature
As I can see torchflare is currently supports only CPU and a single GPU for training, but I think we could use hugging face accelerate to scale it to DDP and TPU

## Why should the feature be added ?
To train bigger and complex models

## Pitch

A clear description of what you want to happen.

**Comment by Atharva-Phatak** [comment]
Sounds good lets start working on it then.
